-- CreateTable
CREATE TABLE `contaspagar` (
    `nro_lanc_cop` INTEGER NOT NULL AUTO_INCREMENT,
    `nro_pro` INTEGER NULL,
    `ano_pro` INTEGER NULL,
    `cod_him` VARCHAR(5) NULL,
    `cod_classconta` INTEGER NULL,
    `cod_banco` CHAR(3) NULL,
    `cod_emp` INTEGER NULL,
    `dt_lanc_cop` DATETIME(0) NULL,
    `dt_vcto_cop` DATETIME(0) NULL,
    `comp_him_cop` VARCHAR(255) NULL,
    `vlr_cop` DECIMAL(10, 2) NULL,
    `credor_cop` INTEGER NOT NULL DEFAULT 0,
    `dt_pgto_cop` DATETIME(0) NULL,
    `dt_receb_cop` DATETIME(0) NULL,
    `dt_prog_cop` DATETIME(0) NULL,
    `vlr_pgto_cop` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `vlr_acre_desc_cop` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `VlrME_Acre_Desc_Cop` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `moeda_vlrme_cop` INTEGER NULL,
    `Moeda_VlrME_Pgto_Cop` INTEGER NULL,
    `vlrme_cop` DECIMAL(10, 2) NULL,
    `vlrme_pgto_cop` DECIMAL(10, 2) NULL,
    `paridade_vlrme_cop` DECIMAL(12, 7) NULL,
    `paridade_vlrme_pgto_cop` DECIMAL(12, 7) NULL,
    `coeficiente_conversao_cop` DECIMAL(12, 7) NULL,
    `variacaocambial_cop` DECIMAL(12, 2) NULL,
    `nro_cheque_cop` VARCHAR(20) NULL,
    `nro_lanc_fif` INTEGER NULL,
    `obs_cop` VARCHAR(255) NULL,
    `unidadenegocioid` INTEGER NULL,
    `inssretidovalor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `irrfretidovalor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `pisretidovalor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `cofinsretidovalor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `csllretidovalor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `ISSRetidoValor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `lote` VARCHAR(20) NULL,
    `autorizado` BOOLEAN NOT NULL DEFAULT false,
    `notafiscalid` INTEGER NULL,
    `faturaservicoid` INTEGER NULL,
    `info_cop` VARCHAR(128) NULL,
    `cobrancabancaria` DECIMAL(10, 2) NULL,
    `ReciboNumero` INTEGER NULL,
    `StatementFaturaServicoId` INTEGER NULL,
    `NotaFiscalItemId` INTEGER NULL,
    `CodigoContabil` VARCHAR(16) NULL,
    `IOFRetidoValor` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    `ContasReceberId` INTEGER NULL,
    `LiquidacaoFormaPagamento` SMALLINT NULL,
    `ReciboId` INTEGER NULL,
    `ProgramacaoCambialBase` CHAR(1) NULL,
    `ProgramacaoCambialDias` INTEGER NULL,
    `ProgramacaoCambialObs` VARCHAR(255) NULL,
    `ProgramacaoCambialPercParcela` DECIMAL(12, 5) NULL,
    `EstaLancadoBanco` BOOLEAN NOT NULL DEFAULT false,
    `OrigemId` VARCHAR(16) NULL,
    `CCambioNumero` VARCHAR(32) NULL,
    `RefDocTipo` VARCHAR(32) NULL,
    `RefDocNumero` VARCHAR(32) NULL,
    `RefDocItemLC` VARCHAR(32) NULL,
    `InclusaoUsuarioId` INTEGER NULL,

    INDEX `AK_contaspagar_cod_banco`(`cod_banco`),
    INDEX `AK_contaspagar_cod_classconta`(`cod_classconta`),
    INDEX `AK_contaspagar_cod_emp`(`cod_emp`),
    INDEX `AK_contaspagar_cod_him`(`cod_him`),
    INDEX `AK_contaspagar_comp_him_cop`(`comp_him_cop`),
    INDEX `AK_contaspagar_contasreceberid`(`ContasReceberId`),
    INDEX `AK_contaspagar_credor_cop`(`credor_cop`),
    INDEX `AK_contaspagar_dt_lanc_cop`(`dt_lanc_cop`),
    INDEX `AK_contaspagar_dt_pgto_cop`(`dt_pgto_cop`),
    INDEX `AK_contaspagar_dt_prog_cop`(`dt_prog_cop`),
    INDEX `AK_contaspagar_dt_vcto_cop`(`dt_vcto_cop`),
    INDEX `AK_contaspagar_faturaservicoid`(`faturaservicoid`),
    INDEX `AK_contaspagar_inclusaousuarioid`(`InclusaoUsuarioId`),
    INDEX `AK_contaspagar_info_cop`(`info_cop`),
    INDEX `AK_contaspagar_lote`(`lote`),
    INDEX `AK_contaspagar_moeda_vlrme_cop`(`moeda_vlrme_cop`),
    INDEX `AK_contaspagar_moeda_vlrme_pgto_cop`(`Moeda_VlrME_Pgto_Cop`),
    INDEX `AK_contaspagar_notafiscalid`(`notafiscalid`),
    INDEX `AK_contaspagar_notafiscalitemid`(`NotaFiscalItemId`),
    INDEX `AK_contaspagar_nro_lanc_fif`(`nro_lanc_fif`),
    INDEX `AK_contaspagar_nro_pro_ano_pro`(`nro_pro`, `ano_pro`),
    INDEX `AK_contaspagar_reciboid`(`ReciboId`),
    INDEX `AK_contaspagar_statementfaturaservicoid`(`StatementFaturaServicoId`),
    INDEX `AK_contaspagar_unidadenegocioid`(`unidadenegocioid`),
    PRIMARY KEY (`nro_lanc_cop`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Extrato` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `data` VARCHAR(191) NOT NULL,
    `descricao` VARCHAR(191) NOT NULL,
    `identificacao` VARCHAR(191) NOT NULL,
    `check` VARCHAR(191) NOT NULL,
    `tipo` VARCHAR(191) NOT NULL,
    `valor` DECIMAL(10, 2) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
